---
- name: Installer Node Exporter
  ansible.builtin.apt:
    name: "{{ node_exporter_package }}"
    state: present
    update_cache: true

- name: Activer Node Exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
